<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="rover_bot">

    <xacro:property name="line_sense_angle"   value="${pi/2.5}"/>

    <xacro:property name="line_sense_mode"   value="true"/>

    <joint name="cam_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="cam_link"/>
        <xacro:if value="${line_sense_mode}">
            <origin xyz="0.22 0 0" rpy="0 ${line_sense_angle} 0"/>
        </xacro:if>
        <xacro:unless value="${line_sense_mode}">
            <origin xyz="0.22 0 ${chassis_height+0.01}" rpy="0 ${pi/4} 0"/>
        </xacro:unless>     
    </joint>

    <link name="cam_link">
        <visual>
            <origin xyz="-0.005 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.01" length="0.01"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <visual>
            <origin xyz="-0.015 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.04 0.025" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="-0.01 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.04 0.025"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.0005" x="0.02" y="0.04" z="0.025">
            <origin xyz="-0.01 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <joint name="cam_optical_joint" type="fixed">
        <parent link="cam_link"/>
        <child link="cam_optical_link"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="cam_optical_link"/>





    <gazebo reference="cam_link">
        <material>Gazebo/DarkGrey</material>

        <sensor type="camera" name="camera">
            <visualize>$(arg cam_visual)</visualize>
            <update_rate>15.0</update_rate>
            <camera name="cam">
                <horizontal_fov>1.4</horizontal_fov>
                <image>
                    <width>320</width>
                    <height>240</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>5</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="rgb_cam_plugin" filename="libgazebo_ros_camera.so">
                <camera_name>cam</camera_name>
                <frame_name>cam_optical_link</frame_name>
                <hack_baseline>0.2</hack_baseline>
            </plugin>
        </sensor>
    </gazebo>
 

  
</robot>